---
plugins:
  vagrant-vbguest: 0.12.0
  vagrant-hostmanager: 1.8.5
  vagrant-share: 1.1.5
  vagrant-librarian-puppet: 0.9.2
  vagrant-puppet-install: 4.0.1
  vagrant-persistent-storage: 0.0.20
vbguest: 
  enable: false
hostmanager:
  enable: true
  manage_host: true
  manage_guest: true
puppet:
  enable: true
  version: '4.8.0'
  puppet_dir: 'puppet'
persistent-storage:
  enable: false
box: bento/centos-7.2
roles:
  master:
    environment: 'mesos'
    cpu: 1
    memory: 1024
    count: 3
    data:
      enable: false
  slave:
    environment: 'mesos'
    cpu: 1
    memory: 2048
    count: 2
    data:
      enable: false